# Generated by Django 2.2.1 on 2019-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('records', models.SmallIntegerField(verbose_name='积分')),
                ('treasure', models.SmallIntegerField(verbose_name='财富')),
            ],
        ),
        migrations.CreateModel(
            name='trends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('article', models.TextField(verbose_name='内容')),
                ('uid', models.ForeignKey(on_delete='CASCADE', to='server.customer')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('title', models.CharField(max_length=12, verbose_name='标题')),
                ('article', models.TextField(verbose_name='内容')),
                ('uid', models.ForeignKey(on_delete='CASCADE', to='server.customer')),
            ],
        ),
    ]
