# Generated by Django 2.2.1 on 2019-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nick_name', models.CharField(max_length=12, verbose_name='昵称')),
                ('discription', models.CharField(max_length=24, null=True, verbose_name='描述')),
                ('fid', models.ForeignKey(on_delete='CASCADE', related_name='fid', to='server.customer')),
                ('uid', models.ForeignKey(on_delete='CASCADE', related_name='uid', to='server.customer')),
            ],
        ),
    ]
