# Generated by Django 2.2.1 on 2019-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190603_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='fconfifm',
            field=models.IntegerField(max_length=2, verbose_name='f确认'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='mconfirm',
            field=models.IntegerField(max_length=2, verbose_name='m确认'),
        ),
    ]
