# Generated by Django 2.2.1 on 2019-06-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190603_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='fconfifm',
            field=models.IntegerField(max_length=12, verbose_name='f确认'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='mconfirm',
            field=models.IntegerField(max_length=12, verbose_name='m确认'),
        ),
    ]
